### ISSUE TITLE
Missing settings.xml?

### ISSUE THREAD

**Issue by t-oster** [haum/visicut-settings#1]
Hi, when downloading your settings via VisiCut I get an error because no settings.xml is included. Is this intentional? why?

**Comment by JackDesBwa** [comment]
I did not followed this subject, but it has been a while since the initial configuration was done.
Perhaps something has changed in the requirements of the configuration since then.
I cannot check this week myself, but if nobody else does it in the meantime, I will have a look the next time I go to the lab.

**Comment by jblb** [comment]
I dont know why this file was deleted from repos
correct by
https://github.com/haum/visicut-settings/commit/842b4e2767dbb28d47e9f25a3e02d6443bb849fa

**Comment by neomilium** [comment]
This file contains personal data and configuration. For example, it contains recent opened files… so it does not seems relevant to add it in a repository.

@t-oster As this file does not seems to be required to share profiles, materials and laser cutter settings, why putting this file in this repo?
IMHO, as this file contains more user defined settings than setup defined settings this file should be explicitly excluded from import.
@t-oster Could you give your point of view about this?

Thanks.

**Comment by t-oster** [comment]
you are right, it contains a few settings which are not necessary, but there are also important settings like supportedExtensions and available importers. You can remove all unwanted stuff (e.g. the recent files) and set default values for window bounds, but the file has to be present in order for visicut to import the settings sucessfully.
The code is here: https://github.com/t-oster/VisiCut/blob/master/src/main/java/de/thomas_oster/visicut/managers/PreferencesManager.java#L362 feel free to adapt it.
